spring.datasource.url=jdbc:mysql://localhost:3306/secure_document_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=ZmFrZVNlY3JldEtleUZvckpXVFNlY3VyZURvY3VtZW50VmFsaWRhdGlvbg==
jwt.expiration=86400000